<?php
namespace App\Controllers\Api;
use App\Models\JadwalKelasModel;
class JadwalController extends BaseApiController
{
 private JadwalKelasModel $model;public function __construct(){$this->model=new JadwalKelasModel();}
 public function index(){ $q=$this->model->select('jadwal_kelas.*,mata_pelajaran.nama_mata_pelajaran,guru.nama_lengkap AS nama_guru,kelas.nama_kelas')->join('mata_pelajaran','mata_pelajaran.id=jadwal_kelas.mata_pelajaran_id')->join('guru','guru.id=jadwal_kelas.guru_id','left')->join('kelas','kelas.id=jadwal_kelas.kelas_id');if($id=(int)$this->request->getGet('kelas_id'))$q->where('jadwal_kelas.kelas_id',$id);return $this->respond(['data'=>$q->orderBy("FIELD(hari,'Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu')",'',false)->orderBy('jam_mulai')->findAll()]);}
 public function create(){return $this->persist();}
 public function update(int $id){if(!$this->model->find($id))return $this->respond(['ok'=>false,'message'=>'Jadwal tidak ditemukan.'],404);return $this->persist($id);}
 public function delete(int $id){if(!$this->model->find($id))return $this->respond(['ok'=>false,'message'=>'Jadwal tidak ditemukan.'],404);$this->model->delete($id);return $this->respond(['ok'=>true]);}
 public function import(){
  $p=$this->payload();$kelas=(int)($p['kelas_id']??0);$rows=$p['rows']??[];
  if($kelas<1||!is_array($rows)||!count($rows))return $this->respond(['ok'=>false,'message'=>'Data jadwal kosong.'],422);
  $days=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];$db=db_connect();$data=[];
  foreach($rows as $i=>$row){$hari=trim((string)($row['hari']??''));$mulai=substr(trim((string)($row['jam_mulai']??'')),0,5);$selesai=substr(trim((string)($row['jam_selesai']??'')),0,5);$mapel=trim((string)($row['mata_pelajaran']??''));$guru=trim((string)($row['guru']??''));if(!in_array($hari,$days,true)||!preg_match('/^\d{2}:\d{2}$/',$mulai)||!preg_match('/^\d{2}:\d{2}$/',$selesai)||$mulai>=$selesai||$mapel==='')return $this->respond(['ok'=>false,'message'=>'Baris '.($i+2).' tidak valid.'],422);$subject=$db->table('mata_pelajaran')->where('nama_mata_pelajaran',$mapel)->get()->getRowArray();if(!$subject){$db->table('mata_pelajaran')->insert(['nama_mata_pelajaran'=>$mapel,'aktif'=>1]);$subject=['id'=>$db->insertID()];}$teacher=$guru===''?null:$db->table('guru')->where('nama_lengkap',$guru)->get()->getRowArray();$data[]=['kelas_id'=>$kelas,'mata_pelajaran_id'=>(int)$subject['id'],'guru_id'=>$teacher?(int)$teacher['id']:null,'hari'=>$hari,'jam_mulai'=>$mulai,'jam_selesai'=>$selesai,'keterangan'=>null];}
  $db->transStart();$db->table('jadwal_kelas')->where('kelas_id',$kelas)->delete();$db->table('jadwal_kelas')->insertBatch($data);$db->transComplete();if(!$db->transStatus())return $this->respond(['ok'=>false,'message'=>'Import jadwal gagal.'],500);return $this->respond(['ok'=>true,'message'=>count($data).' jadwal berhasil diimpor.']);
 } private function persist(?int $id=null){$p=$this->payload();$e=$this->validatePayload($p,['kelas_id'=>'required|is_natural_no_zero','mata_pelajaran_id'=>'required|is_natural_no_zero','guru_id'=>'permit_empty|is_natural_no_zero','hari'=>'required|in_list[Senin,Selasa,Rabu,Kamis,Jumat,Sabtu,Minggu]','jam_mulai'=>'required|regex_match[/^([01]\\d|2[0-3]):[0-5]\\d(:[0-5]\\d)?$/]','jam_selesai'=>'required|regex_match[/^([01]\\d|2[0-3]):[0-5]\\d(:[0-5]\\d)?$/]','keterangan'=>'permit_empty|max_length[255]']);if($e)return $this->respond(['ok'=>false,'errors'=>$e],422);if($p['jam_mulai']>=$p['jam_selesai'])return $this->respond(['ok'=>false,'message'=>'Jam selesai harus setelah jam mulai.'],422);$d=['kelas_id'=>(int)$p['kelas_id'],'mata_pelajaran_id'=>(int)$p['mata_pelajaran_id'],'guru_id'=>empty($p['guru_id'])?null:(int)$p['guru_id'],'hari'=>$p['hari'],'jam_mulai'=>$p['jam_mulai'],'jam_selesai'=>$p['jam_selesai'],'keterangan'=>trim((string)($p['keterangan']??''))?:null];if($id)$this->model->update($id,$d);else$id=$this->model->insert($d,true);return $this->respond(['ok'=>true,'data'=>$this->model->find($id)],$this->request->getMethod()==='POST'?201:200);}
}