<?php
namespace App\Controllers\Api;
class MaintenanceController extends BaseApiController
{
 public function upload(){ $f=$this->request->getFile('patch'); if(!$f||!$f->isValid()||strtolower($f->getExtension())!=='zip')return $this->respond(['ok'=>false,'message'=>'Pilih file patch ZIP yang valid.'],422); if($f->getSize()>52428800)return $this->respond(['ok'=>false,'message'=>'Ukuran patch maksimal 50 MB.'],422);$d=WRITEPATH.'patches';if(!is_dir($d))mkdir($d,0750,true);$n='patch-'.date('Ymd-His').'.zip';$f->move($d,$n);return $this->respond(['ok'=>true,'name'=>$n,'size'=>filesize($d.DIRECTORY_SEPARATOR.$n)]); }
 public function apply(){ $p=$this->request->getJSON(true)??[];$n=basename((string)($p['name']??''));$path=WRITEPATH.'patches'.DIRECTORY_SEPARATOR.$n;if(!$n||!is_file($path)||strtolower(pathinfo($n,PATHINFO_EXTENSION))!=='zip')return $this->respond(['ok'=>false,'message'=>'Patch tidak ditemukan.'],404);if(!class_exists('ZipArchive'))return $this->respond(['ok'=>false,'message'=>'Ekstensi ZIP PHP belum aktif.'],500);$z=new \ZipArchive();if($z->open($path)!==true)return $this->respond(['ok'=>false,'message'=>'ZIP tidak dapat dibaca.'],422);$ok=['app/','public/','composer.json','composer.lock'];for($i=0;$i<$z->numFiles;$i++){ $e=str_replace('\\','/',$z->getNameIndex($i));if(str_contains($e,'..')||!array_filter($ok,fn($x)=>$e===$x||str_starts_with($e,$x))){$z->close();return $this->respond(['ok'=>false,'message'=>'Isi patch tidak diizinkan.'],422);}}$tmp=WRITEPATH.'patches'.DIRECTORY_SEPARATOR.'extract-'.bin2hex(random_bytes(5));mkdir($tmp,0750,true);$z->extractTo($tmp);$z->close();$backup=WRITEPATH.'patches'.DIRECTORY_SEPARATOR.'backup-'.date('Ymd-His');mkdir($backup,0750,true);foreach(['app','public','composer.json','composer.lock'] as $x){$a=ROOTPATH.$x;if(is_dir($a))$this->copyTree($a,$backup.DIRECTORY_SEPARATOR.$x);elseif(is_file($a))copy($a,$backup.DIRECTORY_SEPARATOR.$x);}foreach(['app','public','composer.json','composer.lock'] as $x){$a=$tmp.DIRECTORY_SEPARATOR.$x;if(is_dir($a))$this->copyTree($a,ROOTPATH.$x);elseif(is_file($a))copy($a,ROOTPATH.$x);}$this->removeTree($tmp);return $this->respond(['ok'=>true,'message'=>'Patch diterapkan. Backup tersimpan: '.basename($backup)]); }
 private function copyTree($a,$b){if(!is_dir($b))mkdir($b,0750,true);foreach(scandir($a) as $x){if($x==='.'||$x==='..')continue;$p=$a.DIRECTORY_SEPARATOR.$x;$q=$b.DIRECTORY_SEPARATOR.$x;if(is_dir($p))$this->copyTree($p,$q);else copy($p,$q);}}
 private function removeTree($d){if(!is_dir($d))return;foreach(scandir($d) as $x){if($x==='.'||$x==='..')continue;$p=$d.DIRECTORY_SEPARATOR.$x;if(is_dir($p))$this->removeTree($p);else unlink($p);}rmdir($d);}
}
