<?php
namespace App\Controllers\Api;
use App\Models\PesanKomunikasiModel;
use App\Models\NotifikasiModel;
class PesanKomunikasiController extends BaseApiController
{
 public function index(){ $kelas=(int)$this->request->getGet('kelas_id');$q=(new PesanKomunikasiModel())->select('pesan_komunikasi.*,siswa.nis,siswa.nama_lengkap')->join('siswa','siswa.id=pesan_komunikasi.siswa_id','left')->where('pesan_komunikasi.kelas_id',$kelas)->orderBy('pesan_komunikasi.id','DESC');return $this->respond(['data'=>$q->paginate(25)]);}
 public function prepare(){ $p=$this->payload();$errors=$this->validatePayload($p,['siswa_id'=>'permit_empty|is_natural_no_zero','kelas_id'=>'required|is_natural_no_zero','pengirim'=>'required|max_length[180]','penerima'=>'required|max_length[180]','nomor_tujuan'=>'required|max_length[30]','isi_pesan'=>'required|max_length[5000]','kategori'=>'permit_empty|max_length[80]']);if($errors)return $this->respond(['ok'=>false,'errors'=>$errors],422);$phone=preg_replace('/\D+/','',(string)$p['nomor_tujuan']);if(str_starts_with($phone,'0'))$phone='62'.substr($phone,1);if(!preg_match('/^62\d{8,15}$/',$phone))return $this->respond(['ok'=>false,'message'=>'Nomor WhatsApp tidak valid.'],422);$data=['siswa_id'=>empty($p['siswa_id'])?null:(int)$p['siswa_id'],'kelas_id'=>(int)$p['kelas_id'],'pengirim'=>trim($p['pengirim']),'penerima'=>trim($p['penerima']),'nomor_tujuan'=>$phone,'isi_pesan'=>trim($p['isi_pesan']),'kategori'=>trim((string)($p['kategori']??''))?:null,'status_pengiriman'=>'Disiapkan','dikirim_pada'=>null,'dibuat_oleh'=>$this->currentUser()['id']];$model=new PesanKomunikasiModel();$id=$model->insert($data,true);return $this->respond(['ok'=>true,'data'=>$model->find($id),'whatsappUrl'=>'https://wa.me/'.$phone.'?text='.rawurlencode($data['isi_pesan'])],201);}
 public function incoming(){ $p=$this->payload();$errors=$this->validatePayload($p,['siswa_id'=>'required|is_natural_no_zero','kelas_id'=>'required|is_natural_no_zero','nomor_tujuan'=>'required|max_length[30]','isi_pesan'=>'required|max_length[5000]']);if($errors)return $this->respond(['ok'=>false,'errors'=>$errors],422);$phone=preg_replace('/\D+/','',(string)$p['nomor_tujuan']);if(str_starts_with($phone,'0'))$phone='62'.substr($phone,1);if(!preg_match('/^62\d{8,15}$/',$phone))return $this->respond(['ok'=>false,'message'=>'Nomor WhatsApp tidak valid.'],422);$student=db_connect()->table('siswa')->select('nama_lengkap')->where(['id'=>(int)$p['siswa_id'],'kelas_id'=>(int)$p['kelas_id']])->get()->getRowArray();if(!$student)return $this->respond(['ok'=>false,'message'=>'Siswa tidak ditemukan pada kelas aktif.'],404);$u=$this->currentUser();$model=new PesanKomunikasiModel();$id=$model->insert(['siswa_id'=>(int)$p['siswa_id'],'kelas_id'=>(int)$p['kelas_id'],'pengirim'=>'Orangtua '.$student['nama_lengkap'],'penerima'=>$u['nama_lengkap']??'Wali Kelas','nomor_tujuan'=>$phone,'isi_pesan'=>(string)$p['isi_pesan'],'kategori'=>'Pesan Masuk WhatsApp','status_pengiriman'=>'Diterima','dikirim_pada'=>date('Y-m-d H:i:s'),'dibuat_oleh'=>(int)$u['id']],true);$receivedAt=date('Y-m-d H:i:s');(new NotifikasiModel())->insert(['pengguna_id'=>(int)$u['id'],'judul'=>'Pesan masuk dari Orangtua '.$student['nama_lengkap'],'isi'=>(string)$p['isi_pesan'],'jenis'=>'WhatsApp Masuk','sudah_dibaca'=>0,'dibuat_pada'=>$receivedAt]);return $this->respond(['ok'=>true,'data'=>$model->find($id)],201);}
 public function opened(int $id){$model=new PesanKomunikasiModel();if(!$model->find($id))return $this->respond(['ok'=>false,'message'=>'Histori pesan tidak ditemukan.'],404);$model->update($id,['status_pengiriman'=>'Dibuka','dikirim_pada'=>date('Y-m-d H:i:s')]);return $this->respond(['ok'=>true,'data'=>$model->find($id)]);}
}